name: Build & Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Run tests
        run: ./gradlew test
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Build
        run: ./gradlew clean build -x test

      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Set up Docker BuildX
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      # Build and push multi-arch image
      - name: Build and push multi-arch image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t hc07car/droni:${{ env.VERSION}} --push .